In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

import numpy as np

import warnings

In [2]:
diamond = pd.read_csv('../data/lol_ranked_10min.csv')

In [3]:
diamond

gameId  blueWins  blueWardsPlaced  blueWardsDestroyed  \
0     4519157822         0               28                   2   
1     4523371949         0               12                   1   
2     4521474530         0               15                   0   
3     4524384067         0               43                   1   
4     4436033771         0               75                   4   
...          ...       ...              ...                 ...   
9874  4527873286         1               17                   2   
9875  4527797466         1               54                   0   
9876  4527713716         0               23                   1   
9877  4527628313         0               14                   4   
9878  4523772935         1               18                   0   

      blueFirstBlood  blueKills  blueDeaths  blueAssists  blueEliteMonsters  \
0                  1          9           6           11                  0   
1                  0          5           5            5                  0   
2                  0          7          11            4                  1   
3                  0          4           5            5                  1   
4                  0          6           6            6                  0   
...              ...        ...         ...          ...                ...   
9874               1          7           4            5                  1   
9875               0          6           4            8                  1   
9876               0          6           7            5                  0   
9877               1          2           3            3                  1   
9878               1          6           6            5                  0   

      blueDragons  blueHeralds  blueTowersDestroyed  blueTotalGold  \
0               0            0                    0          17210   
1               0            0                    0          14712   
2               1            0                    0          16113   
3               0            1                    0          15157   
4               0            0                    0          16400   
...           ...          ...                  ...            ...   
9874            1            0                    0          17765   
9875            1            0                    0          16238   
9876            0            0                    0          15903   
9877            1            0                    0          14459   
9878            0            0                    0          16266   

      blueAvgLevel  blueTotalExperience  blueTotalMinionsKilled  \
0              6.6                17039                     195   
1              6.6                16265                     174   
2              6.4                16221                     186   
3              7.0                17954                     201   
4              7.0                18543                     210   
...            ...                  ...                     ...   
9874           7.2                18967                     211   
9875           7.2                19255                     233   
9876           7.0                18032                     210   
9877           6.6                17229                     224   
9878           7.0                17321                     207   

      blueTotalJungleMinionsKilled  blueGoldDiff  blueExperienceDiff  \
0                               36           643                  -8   
1                               43         -2908               -1173   
2                               46         -1172               -1033   
3                               55         -1321                  -7   
4                               57         -1004                 230   
...                            ...           ...                 ...   
9874                            69          2519                2469   
9875                            48

In [4]:
diamond['blueDeathsCopy'] = diamond['blueDeaths'] 
diamond['blueDeathsCopy'] = diamond.loc[:, 'blueDeaths']

In [5]:
diamond['redDeathsCopy'] = diamond['redDeaths'] 
diamond['redDeathsCopy'] = diamond.loc[:, 'redDeaths']

In [6]:
diamond

gameId  blueWins  blueWardsPlaced  blueWardsDestroyed  \
0     4519157822         0               28                   2   
1     4523371949         0               12                   1   
2     4521474530         0               15                   0   
3     4524384067         0               43                   1   
4     4436033771         0               75                   4   
...          ...       ...              ...                 ...   
9874  4527873286         1               17                   2   
9875  4527797466         1               54                   0   
9876  4527713716         0               23                   1   
9877  4527628313         0               14                   4   
9878  4523772935         1               18                   0   

      blueFirstBlood  blueKills  blueDeaths  blueAssists  blueEliteMonsters  \
0                  1          9           6           11                  0   
1                  0          5           5            5                  0   
2                  0          7          11            4                  1   
3                  0          4           5            5                  1   
4                  0          6           6            6                  0   
...              ...        ...         ...          ...                ...   
9874               1          7           4            5                  1   
9875               0          6           4            8                  1   
9876               0          6           7            5                  0   
9877               1          2           3            3                  1   
9878               1          6           6            5                  0   

      blueDragons  blueHeralds  blueTowersDestroyed  blueTotalGold  \
0               0            0                    0          17210   
1               0            0                    0          14712   
2               1            0                    0          16113   
3               0            1                    0          15157   
4               0            0                    0          16400   
...           ...          ...                  ...            ...   
9874            1            0                    0          17765   
9875            1            0                    0          16238   
9876            0            0                    0          15903   
9877            1            0                    0          14459   
9878            0            0                    0          16266   

      blueAvgLevel  blueTotalExperience  blueTotalMinionsKilled  \
0              6.6                17039                     195   
1              6.6                16265                     174   
2              6.4                16221                     186   
3              7.0                17954                     201   
4              7.0                18543                     210   
...            ...                  ...                     ...   
9874           7.2                18967                     211   
9875           7.2                19255                     233   
9876           7.0                18032                     210   
9877           6.6                17229                     224   
9878           7.0                17321                     207   

      blueTotalJungleMinionsKilled  blueGoldDiff  blueExperienceDiff  \
0                               36           643                  -8   
1                               43         -2908               -1173   
2                               46         -1172               -1033   
3                               55         -1321                  -7   
4                               57         -1004                 230   
...                            ...           ...                 ...   
9874                            69          2519                2469   
9875                            48

In [7]:
print(diamond['blueDeathsCopy'].unique())
print(diamond['redDeathsCopy'].unique())

[ 6  5 11  3 13  7  4  1  9  2  8 10 12 14 17 15  0 16 18 19 22]
[ 9  5  7  4  6 11  3 10  8  2  1 13 12 14  0 15 16 18 17 19 22]


In [8]:
diamond.blueDeathsCopy = diamond.blueDeathsCopy.replace(0, 1)
diamond.redDeathsCopy = diamond.redDeathsCopy.replace(0, 1)

In [9]:
print(diamond['blueDeathsCopy'].unique())
print(diamond['redDeathsCopy'].unique())

[ 6  5 11  3 13  7  4  1  9  2  8 10 12 14 17 15 16 18 19 22]
[ 9  5  7  4  6 11  3 10  8  2  1 13 12 14 15 16 18 17 19 22]


In [10]:
diamond["blueKDA"] = np.nan
diamond["redKDA"] = np.nan

In [11]:
diamond.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9879 entries, 0 to 9878
Data columns (total 44 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   gameId                        9879 non-null   int64  
 1   blueWins                      9879 non-null   int64  
 2   blueWardsPlaced               9879 non-null   int64  
 3   blueWardsDestroyed            9879 non-null   int64  
 4   blueFirstBlood                9879 non-null   int64  
 5   blueKills                     9879 non-null   int64  
 6   blueDeaths                    9879 non-null   int64  
 7   blueAssists                   9879 non-null   int64  
 8   blueEliteMonsters             9879 non-null   int64  
 9   blueDragons                   9879 non-null   int64  
 10  blueHeralds                   9879 non-null   int64  
 11  blueTowersDestroyed           9879 non-null   int64  
 12  blueTotalGold                 9879 non-null   int64  
 13  blu

In [12]:
diamond['blueKDA'] = (diamond['blueKills'] + diamond['blueAssists']) / diamond['blueDeathsCopy']

In [13]:
diamond['redKDA'] = (diamond['redKills'] + diamond['redAssists']) / diamond['redDeathsCopy']

In [14]:
diamond.head(20)

gameId  blueWins  blueWardsPlaced  blueWardsDestroyed  blueFirstBlood  \
0   4519157822         0               28                   2               1   
1   4523371949         0               12                   1               0   
2   4521474530         0               15                   0               0   
3   4524384067         0               43                   1               0   
4   4436033771         0               75                   4               0   
5   4475365709         1               18                   0               0   
6   4493010632         1               18                   3               1   
7   4496759358         0               16                   2               0   
8   4443048030         0               16                   3               0   
9   4509433346         1               13                   1               1   
10  4452162573         0               20                   3               1   
11  4453038156         0               33                   2               1   
12  4515594785         1               18                   1               1   
13  4524924257         0               14                   3               0   
14  4516505202         1               15                   3               1   
15  4482120064         0               17                   1               0   
16  4523758462         1               14                   1               1   
17  4503636905         0               43                   3               0   
18  4486384947         1               21                   4               1   
19  4457103291         0               11                   3               0   

    blueKills  blueDeaths  blueAssists  blueEliteMonsters  blueDragons  \
0           9           6           11                  0            0   
1           5           5            5                  0            0   
2           7          11            4                  1            1   
3           4           5            5                  1            0   
4           6           6            6                  0            0   
5           5           3            6                  1            1   
6           7           6            7                  1            1   
7           5          13            3                  0            0   
8           7           7            8                  0            0   
9           4           5            5                  1            1   
10          4           4            6                  0            0   
11         11          11            7                  1            0   
12          7           1           11                  1            1   
13          4           9            1                  1            0   
14          4           4            4                  0            0   
15          3           7            3                  0            0   
16         10           2            8                  0            0   
17          3           7            3                  1            0   
18          5           4           11                  0            0   
19          5           9            5                  0            0   

    blueHeralds  blueTowersDestroyed  blueTotalGold  blueAvgLevel  \
0             0                    0          17210           6.6   
1             0                    0          14712           6.6   
2             0                    0          16113           6.4   
3             1                    0          15157           7.0   
4             0                    0          16400           7.0   
5             0                    0          15899           7.0   
6             0                    0          16874           6.8   
7             0                    0          15305           6.4   
8             0                    0          16401           7.2   
9             0                    0          15057          

In [16]:
kda = diamond[['blueKDA','blueKills','blueDeaths','blueAssists','redKDA','redKills','redDeaths','redAssists']]

In [19]:
kda.head(50)

blueKDA  blueKills  blueDeaths  blueAssists     redKDA  redKills  \
0    3.333333          9           6           11   1.555556         6   
1    2.000000          5           5            5   1.400000         5   
2    1.000000          7          11            4   3.571429        11   
3    1.800000          4           5            5   3.750000         5   
4    2.000000          6           6            6   2.166667         6   
5    3.666667          5           3            6   1.000000         3   
6    2.333333          7           6            7   2.142857         6   
7    0.615385          5          13            3   4.800000        13   
8    2.142857          7           7            8   1.714286         7   
9    1.800000          4           5            5   2.250000         5   
10   2.500000          4           4            6   2.250000         4   
11   1.636364         11          11            7   1.818182        11   
12  18.000000          7           1           11   0.285714         1   
13   0.555556          4           9            1   5.000000         9   
14   2.000000          4           4            4   1.750000         4   
15   0.857143          3           7            3   6.666667         7   
16   9.000000         10           2            8   0.400000         2   
17   0.857143          3           7            3   4.333333         7   
18   4.000000          5           4           11   1.400000         4   
19   1.111111          5           9            5   3.600000         9   
20   4.333333         11           6           15   0.909091         6   
21   0.692308          4          13            5   6.750000        13   
22   1.166667          4           6            3   4.000000         6   
23   2.666667          4           3            4   1.500000         3   
24   1.777778          6           9           10   3.666667         9   
25   1.000000          4           8            4   5.250000         8   
26   2.833333          8           6            9   1.125000         6   
27   4.000000          7           4            9   0.857143         4   
28   3.500000          8           6           13   2.125000         6   
29   0.625000          3           8            2   6.666667         8   
30   4.750000          9           4           10   0.666667         4   
31   5.500000          5           2            6   0.800000         2   
32   3.250000          6           4            7   1.333333         4   
33   2.250000          5           4            4   1.600000         4   
34   2.500000          6           4            4   1.500000         4   
35   2.250000          3           4            6   3.666667         4   
36   0.500000          2           8            2   6.500000         8   
37   1.500000          5           6            4   2.400000         6   
38   1.333333          7           9            5   2.571429         9   
39   1.000000          3           6            3   4.000000         6   
40   0.636364          4          11            3   6.750000        11   
41   3.666667         10           6           12   1.300000         6   
42   3.833333          9           6           14   1.333333         6   
43   1.600000          5           5            3   1.800000         5   
44   1.250000          3           4            2   2.000000         4   
45   0.100000          1          10            0  16.000000        10   
46  10.000000         11           2            9   0.363636         2   
47   3.250000          8           4            5   1.125000         4   
48   1.333333          2           3            2   2.000000         3   
49   2.600000          5           5            8   2.200000         5   

    redDeaths  redAssists  
0           9           8  
1           5           2  
2           7          14  
3           4          10  
4           6           7  
5           5           2  
6           7           9  
7      

In [20]:
diamond.to_csv('../data/datawithKDA.csv', sep=',', index=False)